# Generated by Django 4.2.4 on 2023-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('trade', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('self_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'block',
                'managed': False,
            },
        ),
    ]
