# Generated by Django 4.2.4 on 2023-12-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
    ]
