# Generated by Django 4.2.4 on 2023-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=255, verbose_name='角色名称')),
                ('cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色图标')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('del_flag', models.IntegerField(default=1, verbose_name='软删除 0代表删除 1代表正常用户')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_role',
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
