# Generated by Django 4.2.4 on 2023-12-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_mentalmessages_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mentalmessages',
            table=None,
        ),
    ]
