# Generated by Django 4.2.4 on 2023-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('picture_path', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('del_flag', models.IntegerField(default=1)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('pho', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
